### ISSUE TITLE
[Bug] Killing app leaves recent page when using stock pixel launcher as default launcher

### ISSUE THREAD

**Issue by ohmybahgosh** [siavash79/PixelXpert#776] opened 2024-01-02 21:20 UTC
### Describe the issue

[Bug] Swipe up to kill app triggers empty recent app screen

### Steps to reproduce

So far only reproducible when user is on stock pixel launcher as default launcher 

Way to reproduce:
Navigation > Gesture > Swipe Up > Kill forground app

![Screenshot_20240101-152447](https://github.com/siavash79/PixelXpert/assets/77786782/375370f4-8dfd-4025-bd92-52ab452832be)
![Screenshot_20240101-152456](https://github.com/siavash79/PixelXpert/assets/77786782/a2b4af90-2108-481a-bbb7-9b399e7592aa)

### Expected behavior

For the current app to close, not bring up empty recent screen

### Your device setup (Please take some time to give correct information here)

Device Info:
Pixel 7
A14 Latest Dec Update
Stock Pixel Launcher

Latest Canary build of PixelXpert 

### Logs

[LSPosed_2024-01-02T16_19_54.404958.zip](https://github.com/siavash79/PixelXpert/files/13814006/LSPosed_2024-01-02T16_19_54.404958.zip)

**Comment by ohmybahgosh** [comment] 2024-01-24 12:17
Is any further info needed from me?  This has always been a critical aspect of the app for me.

**Comment by EleoXDA** [comment] 2024-01-24 13:30
> Is any further info needed from me? This has always been a critical aspect of the app for me.

the issue is neither a serious bug nor anything critical. It only happens when user has only Pixel Launcher.

**Comment by EleoXDA** [comment] 2024-01-24 13:31
It will be investigated when no more serious bugs left

**Comment by ohmybahgosh** [comment] 2024-01-26 18:27
> > Is any further info needed from me?  This has always been a critical aspect of the app for me.
> 
> The problem is deciding what to do when the foreground app is killed. Switch to the previous app or go back home?
> 
> This is something I can't decide on yet

My two cents..

After killing, go to home :)

**Comment by EleoXDA** [comment] 2024-01-26 21:42
> > Is any further info needed from me?  This has always been a critical aspect of the app for me.
> 
> The problem is deciding what to do when the foreground app is killed. Switch to the previous app or go back home?
> 
> This is something I can't decide on yet

I would say home too

**Closed** 2024-02-12 20:10 UTC

**Comment by ohmybahgosh** [comment] 2024-02-13 01:01
What commit fixed this?

**Comment by EleoXDA** [comment] 2024-02-13 09:18
> What commit fixed this?

the last one
