### ISSUE TITLE
taskbar does not appear when auto-hide is on / taskbar auto-hide crashes pixel launcher

### ISSUE THREAD

**Issue by elvisisvan** [siavash79/PixelXpert#815] opened 2024-03-27 15:14 UTC
### Describe the issue

issue: inconsistent taskbar; taskbar forced enable, auto-hide on, taskbar only appear briefly after reboot right after discarding "pixel launcher keeps stopping" prompt alert then disappear completely

### Steps to reproduce

choose "forced enabled" under "android taskbar" and choose "on" under auto-hide

### Expected behavior

taskbar appear in homescreen, hide away when using apps

### Your device setup (Please take some time to give correct information here)

device: google pixel 7 pro
android version: 13 (TQ3A.230705.001)
magisk version: 27.0
lsposed version: 1.9.2 (7024)
pixelxpert version: 3.3.2 (stable)

### Logs

[LSPosed_2024-03-27T07_59_26.260215 (pixelxpert).zip](https://github.com/siavash79/PixelXpert/files/14775295/LSPosed_2024-03-27T07_59_26.260215.pixelxpert.zip)

screen record for demonstration: https://sendvid.com/kg1y19bc

**Comment by EleoXDA** [comment] 2024-03-29 08:03
> ### Describe the issue
> 
> issue: inconsistent taskbar; taskbar forced enable, auto-hide on, taskbar only appear briefly after reboot right after discarding "pixel launcher keeps stopping" prompt alert then disappear completely
> 
> ### Steps to reproduce
> 
> choose "forced enabled" under "android taskbar" and choose "on" under auto-hide
> 
> ### Expected behavior
> 
> taskbar appear in homescreen, hide away when using apps
> 
> ### Your device setup (Please take some time to give correct information here)
> 
> device: google pixel 7 pro
> android version: 13 (TQ3A.230705.001)
> magisk version: 27.0
> lsposed version: 1.9.2 (7024)
> pixelxpert version: 3.3.2 (stable)
> 
> ### Logs
> 
> [LSPosed_2024-03-27T07_59_26.260215 (pixelxpert).zip](https://github.com/siavash79/PixelXpert/files/14775295/LSPosed_2024-03-27T07_59_26.260215.pixelxpert.zip)

It shows that you are on May 2023 security patch. Is it correct?

**Comment by elvisisvan** [comment] 2024-03-29 15:18
> > ### Describe the issue
> > issue: inconsistent taskbar; taskbar forced enable, auto-hide on, taskbar only appear briefly after reboot right after discarding "pixel launcher keeps stopping" prompt alert then disappear completely
> > ### Steps to reproduce
> > choose "forced enabled" under "android taskbar" and choose "on" under auto-hide
> > ### Expected behavior
> > taskbar appear in homescreen, hide away when using apps
> > ### Your device setup (Please take some time to give correct information here)
> > device: google pixel 7 pro
> > android version: 13 (TQ3A.230705.001)
> > magisk version: 27.0
> > lsposed version: 1.9.2 (7024)
> > pixelxpert version: 3.3.2 (stable)
> > ### Logs
> > [LSPosed_2024-03-27T07_59_26.260215 (pixelxpert).zip](https://github.com/siavash79/PixelXpert/files/14775295/LSPosed_2024-03-27T07_59_26.260215.pixelxpert.zip)
> 
> It shows that you are on May 2023 security patch. Is it correct?

by "it" do you mean the lsposed logs? and security patch of android version build of pixelxpert?

i couldn't attached a video to the post to demonstrate the issue because github's 10mb limit so i uploaded elsewhere, this screen record i made immediately after reboot https://sendvid.com/kg1y19bc

**Comment by EleoXDA** [comment] 2024-03-29 19:42
> > It shows that you are on May 2023 security patch. Is it correct?
> 
> by "it" do you mean the lsposed logs? and security patch of android version build of pixelxpert?

By "it" I mean the logs and your report. You are using a google pixel 7 pro, a device that receives updates every month, and deliberately not updating the firmware? Just want to be sure about the firmware version on your Google Pixel device.

**Comment by elvisisvan** [comment] 2024-03-30 05:12
> By "it" I mean the logs and your report. You are using a google pixel 7 pro, a device that receives updates every month, and deliberately not updating the firmware? Just want to be sure about the firmware version on your Google Pixel device.

yes, this device is still on an old security patch from july 2023

**Comment by EleoXDA** [comment] 2024-04-14 15:38
Is it fixed now? Can't reproduce on a15.

**Comment by siavash79** [comment] 2024-04-16 16:58
Some versions of android don't have the auto hide taskbar included in them. You might want to use the static one instead

**Closed by siavash79** 2024-04-16 16:58 UTC
