### ISSUE TITLE
[Bug] Missing "Reduce space on the keyboard"

### ISSUE THREAD

**Issue by asamofal** [siavash79/PixelXpert#725] opened 2023-11-03 09:43 UTC
### Describe the issue

What happen to "Reduce space on the keyboard" option? It's gone in the last release. Is it removed?

### Steps to reproduce

This option still appears in the search result _(by the way, why is it there 4 times?)_ but I don't see it in the `Gesture navigation` section.

<img src="https://github.com/siavash79/PixelXpert/assets/2729547/1d8cd5fa-4ad2-430b-8614-9a54eb125498" width="400">

### Your device setup (Please take some time to give correct information here)

- Google Pixel 7 
- Stock Firmware, Android 14 (UP1A.231005.007)
- Magisk v 26.3 (Stable)
- PixelXpert 3.1.0
- LSPosed v1.9.2

**Comment by EleoXDA** [comment] 2023-11-03 10:41
It is not a bug. The feature is removed. Use other modules for that please

**Comment by EleoXDA** [comment] 2023-11-03 10:42
Indexing should be fixed

**Comment by EleoXDA** [comment] 2023-11-04 07:14
Fixed

![Screenshot_20231104-081340.png](https://github.com/siavash79/PixelXpert/assets/27622683/e692fa0a-9b3b-4c8e-86f5-5148a1cfca0d)

**Closed** 2023-11-04 07:14 UTC
